coverage:
  status:
    project:
      default:
        target: auto
        threshold: 10%
    patch:
      default:
        target: auto
        threshold: 10%
comment:
  layout: 'diff, flags, files'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
ignore:
  - 'app'
  - 'di'
  - 'drizzle'
  - 'test/coverage'
  - ./*.mjs
  - ./*.ts
  - src/entities
  - src/infrastructure/repositories/*.ts
  - src/infrastructure/services/*.ts
